### PR TITLE
feat: support script for SURE-5880

### PR DESCRIPTION
**Pull request by richardcase**
This includes two support scripts that can be used to upgrade an EKS cluster using the Rancher API or Kubectl. It's designed for Rancher 2.6.10 where there is a UI bug that prevents users from doing this. This is a temporary solution until the bug fix is released in 2.6.11.

See the README.md files for usage instructions, requirements and a demo.

> If upgrading from EKS 1.22 to 1.23 its advised that you enable the EKS EBS CSI Driver before upgrading.  This can be done using the AWS console or using the support tool from #217.

**This should only be used under the direction of SUSE support** 

Relates To: https://github.com/rancher/eks-operator/issues/103

### CODE REVIEW

**Review by alexander-demicev — APPROVED** [review]

**Review by thehejik — APPROVED** [review]
I tested this slightly for updating a downstream EKS cluster from 1.22 to 1.23 on rancher:v2.6.8 (running also on EKS). Everything was done according to the README.md.

**Comment by thehejik** [comment]
Seems that only control-plane has been updated.

* upgrade the downstream EKS v1.22 cluster to v1.23 by:
```
./eks-support.sh upgrade -t $RANCHER_TOKEN --endpoint $RANCHER_API --from 1.22 --to 1.23 --name $CLUSTER
[] ONLY USE THIS SCRIPT AS DIRECTED BY SUSE SUPPORT
[] Upgrading cluster th-downstream1 to version 1.23
[] Getting details for cluster th-downstream1
[] Checking cluster is active and with expected version 1.22
[] Sending request to upgrade cluster th-downstream1 (c-frpgz) to 1.23
```
* After a while I checked Rancher UI and the downstream cluster reported new version v1.23

But then I noticed that actually only control-plane was updated, worker nodes are still using v1.22 for some reason.

image

**Comment by richardcase** [comment]
> But then I noticed that actually only control-plane was updated, worker nodes are still using v1.22 for some reason.

This is intentional. For the customers' scenario, they upgrade the node groups via a different mechanism and only needed a script to update the control plane.

**Comment by thehejik** [comment]
@richardcase thanks for confirmation, then the script is working as expected and my approval is legit.

**Comment by richardcase** [comment]
The customer asked for something that would work against the Rancher API, so thats what we did.

**Comment by richardcase** [comment]
Converting back to draft whilst more changes are made for kev1

**Comment by richardcase** [comment]
@dkeightley - for a kev1 cluster i think your suggestion is the best, thanks. 

I have created an update to the original script that uses the api and also a new script that uses `kubectl patch`.

**Review by dkeightley — APPROVED** [review]
Tested eks-upgrade-using-kubectl which is the important focus:

```bash
# ./eks-support.sh list -k ~/.kube/config --kev1
[] ONLY USE THIS SCRIPT AS DIRECTED BY SUSE SUPPORT
[] Getting EKS clusters from Rancher (kev1=true)
[] Found the following clusters
c-sz2jz  d-eks-v1  1.22  eks
local    local     rke2

# ./eks-support.sh upgrade -k ~/.kube/config --from 1.22 --to 1.23 --name d-eks-v1 --kev1
[] ONLY USE THIS SCRIPT AS DIRECTED BY SUSE SUPPORT
[] Upgrading cluster d-eks-v1 to version 1.23 using kubectl (kev1=true)
[] Getting details for cluster d-eks-v1
[] Checking cluster is active and with expected version 1.22
[] Patching Rancher cluster to upgrade cluster d-eks-v1 (c-sz2jz) to 1.23
[] Patched cluster successfully
```

**Note** a follow-up CloudFormation stack update will be needed for each EKS cluster after the control plane upgrade completes (actioned by the above), the `NodeImageId` parameter should be updated with a [matching AMI for the k8s version and region](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html).

Care should be taken when updating the stack if out-of-band changes have been made, such as adjusting the ASG capacity values, review the current ASG to compare.

The above could be added to the README for `eks-upgrade-using-kubectl`

**Pull request merged**
