### PR TITLE
Adding drone pipeline for testing

### PR DESCRIPTION
**Pull request by mattmattox**
Adding the drone build file to start publishing our images in the rancher org.

### CODE REVIEW

**Comment by dnoland1** [comment]
You have duplicate step names which is causing the build to fail. See https://drone-publish.rancher.io/rancherlabs/support-tools/1

**Comment by mattmattox** [comment]
@dnoland1 I fixed the duplicate step.

Now it's currently erroring during the docker push which is pending https://github.com/rancherlabs/eio/issues/351 and https://github.com/rancherlabs/drone-publishing-setup/pull/57

**Comment by mattmattox** [comment]
@dnoland1 rancherlabs/eio#351 and rancherlabs/drone-publishing-setup#57 are done
The build is now failing because the docker hub creds are now open to PRs.
https://drone-publish.rancher.io/rancherlabs/support-tools/3/1/2

**Comment by dnoland1** [comment]
@mattmattox I believe if you add the following to the step, it will only run on merge and not for a PR:
```yaml
  when:
    branch: master
    event:
      include:
      - push
```
See https://docs.drone.io/pipeline/docker/syntax/conditions/#by-event

**Comment by mattmattox** [comment]
@dnoland1 That worked and the build is now passing.

**Review by dnoland1 — APPROVED** [review]
@mattmattox There's not really a good way of testing this that I know of without merging the PR. So will go ahead and merge it.

**Comment by dnoland1** [comment]
Looks like build was successful - https://drone-publish.rancher.io/rancherlabs/support-tools/4/1/2

Also verified that I can docker pull both `rancher/bad-ingress-scanner` and `rancher/change-nodetemplate-owner`

**Pull request merged**
