### PR TITLE
Adding NGINX-to-pods-check

### PR DESCRIPTION
**Pull request by mattmattox**
This script is designed to walk through all the ingresses in a cluster and test that it can curl the backend pods from the NGINX pods. This is mainly done to verify the overlay network is working along with checking the overall configuration.

Importing from https://github.com/mattmattox/NGINX-to-pods-check

### CODE REVIEW

**Review by dnoland1 — CHANGES_REQUESTED** [review]
Example doesn't work:
```
# kubectl apply -f example-deployment.yml
deployment.apps/webserver-good created
error: error validating "example-deployment.yml": error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): missing required field "name" in io.k8s.api.core.v1.Container; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by mattmattox** [comment]
@dnoland1 I fixed the example deployment. I had a copy-paste error.

**Comment by dnoland1** [comment]
Would be nice to use v1 ingresss instead of the deprecated v1beta1.
```
# kubectl apply -f example-deployment.yml
deployment.apps/webserver-good created
deployment.apps/webserver-bad created
service/webserver-good created
service/webserver-bad created
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
ingress.extensions/webserver-good created
ingress.extensions/webserver-bad created
```
The check.sh test works:
```
# ./check.sh
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
####################################################
Pod: webserver-bad-59b97b6cc9-kff82
PodIP: 10.42.0.13
Port: 80
Endpoint: webserver-bad
Ingress: webserver-bad
Ingress Pod: nginx-ingress-controller-4vhl4
Node: ip-10-0-7-10
Status: Fail!
####################################################
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
####################################################
Pod: webserver-good-7cd9bdbbd4-sfx2w
PodIP: 10.42.0.12
Port: 80
Endpoint: webserver-good
Ingress: webserver-good
Ingress Pod: nginx-ingress-controller-4vhl4
Node: ip-10-0-7-10
Status: Pass!
####################################################
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

**Review by dnoland1 — APPROVED** [review]
LGTM

**Pull request merged**
