### PR TITLE
Rename usage collector script to systems information

### PR DESCRIPTION
**Pull request by dnoland1**

### CODE REVIEW

**Comment by jambajaar** [comment]
@dnoland1  -- the script should be `systems_summary.sh` and the folder it is under should be `systems_information`.

The script should not be `systems_information.sh`

**Comment by dnoland1** [comment]
Renamed script to `systems_summary.sh`

**Comment by jambajaar** [comment]
LGTM @dnoland1

**Comment by jambajaar** [comment]
LGTM @dnoland1

**Pull request merged**
