### PR TITLE
Add rotate-tokens script

### PR DESCRIPTION
**Pull request by macedogm**
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

### CODE REVIEW

**Review by cmurphy — APPROVED** [review]

**Comment by dnoland1** [comment]
@cmurphy did you test this script and if so, can you provide details on the testing?

**Comment by macedogm** [comment]
@ganomi46 and @dkeightley if you need further context about this, including QA tests, please reach out to me directly in Slack. We need this PR merged today. I've already provided the context for @dnoland1.

**Review by dnoland1 — APPROVED** [review]
Based on QA test results, merging.

**Comment by dkeightley** [comment]
Just got to this, it's merged however during basic testing I added the below for consideration, it would be great to resolve (1).

1.  Each script in this repo usually has a readme to explain basic details and usage, why/when you would run it, Rancher version support, disclaimer etc.
2.  Should the cleanup function also cleanup the `./kubeconfig` directory?

Unsure why, but during testing I had to kill the `kubectl rollout status` command each time for the script to proceed.

```bash
+ kubectl --namespace cattle-system rollout status deployment cattle-cluster-agent
Waiting for deployment "cattle-cluster-agent" rollout to finish: 1 out of 2 new replicas have been updated...
Waiting for deployment "cattle-cluster-agent" rollout to finish: 1 out of 2 new replicas have been updated...
deployment "cattle-cluster-agent" successfully rolled out
  [...]
```

**Comment by cmurphy** [comment]
@dkeightley I added a README here: https://github.com/rancherlabs/support-tools/pull/184

I thought about cleaning up the kubeconfig directory but opted on the side of non-destructiveness. I added a note about it in the README. I could change it, but then we should go through another round of QA on it.

It looks like the rollout status command returned successfully, so it may be hanging on another command. You can set the DEBUG variable to see that command it is trying to run.

**Pull request merged**
