### PR TITLE
add provisioning related crds for offline debugging

### PR DESCRIPTION
**Pull request by aemneina**
tested with rke1 so far. needs further testing for k3s/rke2.

### CODE REVIEW

**Comment by aemneina** [comment]
just checked k3s, and the kubeconfig in use doesnt have adequate permissions. need to fix that

**Comment by aemneina** [comment]
added correct k3s and rke2 kubeconfigs. should be g2g

**Comment by dkeightley** [comment]
Dropping two notes covered in slack:
- We could detect if it’s a local cluster, so this function is only run on local clusters
- Set the objects to be collected in an env var, and loop through them - the naming for the file would just probably need to change to the object name

**Review by dkeightley — APPROVED** [review]
Tested on RKE1 & RKE2

**Pull request merged**
