### PR TITLE
Profile collector

### PR DESCRIPTION
**Pull request by rbreddy**
Establishing a new script to collect Rancher golang profiles (https://pkg.go.dev/runtime/pprof)

### CODE REVIEW

**Review by axeal — CHANGES_REQUESTED** [review]
Could you please add a README.md file explaining the purpose of the script, an example of its usage, and details on any arguments?

I see several parameters, such as APP at the top of the script, if the user is expected to set these it would be better if this could be passed as an argument to the script. For and example of how this is done in the log collector see https://github.com/rancherlabs/support-tools/blob/master/collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh#L1038

**Comment by rbreddy** [comment]
> Could you please add a README.md file explaining the purpose of the script, an example of its usage, and details on any arguments?
> 
> I see several parameters, such as APP at the top of the script, if the user is expected to set these it would be better if this could be passed as an argument to the script. For and example of how this is done in the log collector see https://github.com/rancherlabs/support-tools/blob/master/collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh#L1038

Hello @axeal, added the README and passing as parameters for most of arguments (for now aks blobs will be kept to be hardcoded)

**Review by kourosh7 — APPROVED** [review]
I have tested the script and the arguments. LGTM.

**Comment by Tejeev** [comment]
@axeal How's this looking to you?  Are we good to merge now?

**Comment by moio** [comment]
Please, can this be merged? I came across multiple cases that need this in the last month since the PR was first opened, and would love to give customers and colleagues an official link.

Any things can always be improved later by follow-up PRs if needed.

Thanks in advance

**Pull request merged**
