### PR TITLE
Sanitise s3 keys, collect sanitised config for k3s

### PR DESCRIPTION
**Pull request by dkeightley**
Tested on RKE2 and k3s where the changes apply.

The etcd keys are not included in the collection of config.yaml

Resolves: https://github.com/rancherlabs/support-tools/issues/235

### CODE REVIEW

**Comment by dkeightley** [comment]
@sadhugit are you able to test and review?

**Comment by sadhugit** [comment]
LGTM, I have tested by adding "etcd-s3-access-key" in /etc/rancher/rke2/config.yaml.d/50-rancher.yaml and it is omitting the access key as per the fix.

**Comment by sadhugit** [comment]
HI, @dkeightley  logic, wise(Grep command ), it is working fine, but when I ran the rancher log collector in the  RKE2 setup, it threw the errors../rancher2_logs_collector.sh
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
./rancher2_logs_collector.sh: line 1: timestamp: command not found
awk: fatal: cannot open file `/etc/rancher/rke2/config.yaml' for reading: No such file or directory

**Comment by dkeightley** [comment]
Rebased off the master branch, ready to merge - @sadhugit can you approve it?

**Review by dnoland1 — CHANGES_REQUESTED** [review]
I'm seeing the token in k3s/k3s.service in the bundle:
```
# grep token k3s/k3s.service -B3 -A3
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--token' \
	'<redacted after running grep>' \
	'--flannel-backend' \
	'wireguard' \
```

**Comment by dkeightley** [comment]
Thanks @dnoland1 I'll add that as well

**Review by sadhugit — APPROVED** [review]
LGTM, I have tested with RKE2 and it's not retrieving  access/secret keys

**Comment by sadhugit** [comment]
/test/ip-172-31-15-248-2023-10-10_05_43_08/rke2$ cat 50-rancher.yaml
{
  "cni": "calico",
  "disable-kube-proxy": false,
  "etcd-expose-metrics": false,
  "etcd-snapshot-retention": 5,
  "etcd-snapshot-schedule-cron": "0 */5 * * *",
  "kube-controller-manager-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager",
    "secure-port=10257"
  ],
  "kube-controller-manager-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager"
  ],
  "kube-scheduler-arg": [
    "cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler",
    "secure-port=10259"
  ],
  "kube-scheduler-extra-mount": [
    "/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler"
  ],
  "node-label": [
    "cattle.io/os=linux",
    "rke.cattle.io/machine=cc0b6b07-13e6-44ff-a5e8-69e91667b6c3"
  ],
  "private-registry": "/etc/rancher/rke2/registries.yaml",
  "protect-kernel-defaults": false,
}

**Review by dnoland1 — APPROVED** [review]
LGTM, token is now redacted:
```
# grep token k3s/k3s.service -B3 -A3
ExecStartPre=-/sbin/modprobe overlay
ExecStart=/usr/local/bin/k3s \
    server \
	'--token' \
	<token redacted>
	'--flannel-backend' \
	'wireguard' \
	'--cluster-cidr' \
```

**Pull request merged**
